name: Build and deploy an updated version of the website

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pandocs
      uses: actions/checkout@v2
      with:
        path: pandocs

    - name: Print debug info
      run: |
        echo ${{ github.ref }}
        echo ${{ github.event.ref }}

    - name: Checkout pandocs gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: pandocs/docs

    - name: Install mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pandocs/requirements.txt

    - name: Build
      working-directory: pandocs/
      env:
        MDBOOK_BUILD__CREATE_MISSING: "false"
      run: |
        mdbook build

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      working-directory: pandocs/docs/pandocs/
      run: |
        mkdir -p -m 700 ~/.ssh
        echo "${{ secrets.SSH_KEY_SECRET }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_ed25519
        git config --local user.name "GitHub Action"
        git config --global user.email "community@gbdev.io"
        git add -A
        git commit -m "Update build"
        git push
